export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f5f5f5]">
      {/* Header */}
      <div className="bg-white border-b border-[#ebebeb]">
        <div className="max-w-[780px] mx-auto px-6 py-5 flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-[#ededff] flex items-center justify-center">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
              <path
                d="M12 2L3 7l9 5 9-5-9-5zM3 17l9 5 9-5M3 12l9 5 9-5"
                stroke="#6b6ef9"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
          <span className="text-[17px] font-bold tracking-tight text-[#111]">
            Clarity<span className="text-[#6b6ef9]">AI</span>
          </span>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-[780px] mx-auto px-6 py-14">

        {/* Hero */}
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 bg-[#ededff] text-[#6b6ef9] text-[12px] font-semibold px-3 py-1.5 rounded-full mb-5 tracking-wide uppercase">
            Legal
          </div>
          <h1 className="text-[38px] font-bold tracking-tight text-[#0f0f0f] leading-tight mb-3">
            Terms & Conditions
          </h1>
          <p className="text-[15px] text-[#999] font-medium">
            Last updated: <span className="text-[#666]">April 27, 2026</span>
          </p>
        </div>

        {/* Intro card */}
        <div className="bg-[#ededff] border border-[#d8d8ff] rounded-2xl px-6 py-5 mb-10">
          <p className="text-[14.5px] text-[#4a4a9a] leading-relaxed">
            Please read these terms carefully before using ClarityAI. By accessing or using our service, you confirm that you have read, understood, and agree to be bound by these terms.
          </p>
        </div>

        {/* Sections */}
        <div className="flex flex-col gap-3">

          {/* Section 1 */}
          <Section number="01" title="Acceptance of Terms">
            <p>By accessing or using ClarityAI ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use our service.</p>
            <p>These terms apply to all visitors, users, and others who access or use the Service. We reserve the right to update these terms at any time, and your continued use of the Service constitutes acceptance of those changes.</p>
          </Section>

          {/* Section 2 */}
          <Section number="02" title="Use of the Service">
            <p>You agree to use ClarityAI only for lawful purposes and in a manner consistent with all applicable local, national, and international laws and regulations.</p>
            <p>You may not:</p>
            <ul>
              <li>Use the Service to harass, abuse, or harm others</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Reverse engineer or attempt to extract the source code</li>
              <li>Use the Service to generate or distribute harmful or misleading content</li>
            </ul>
          </Section>

          {/* Section 3 */}
          <Section number="03" title="Privacy & Data">
            <p>Your privacy matters to us. ClarityAI collects and processes personal data in accordance with our Privacy Policy. By using the Service, you consent to such processing.</p>
            <p>We use Google OAuth for authentication and do not store your password. Your decision sessions are saved securely and associated with your account. You may delete your data at any time by contacting us.</p>
          </Section>

          {/* Section 4 */}
          <Section number="04" title="AI-Generated Advice">
            <p>ClarityAI provides AI-assisted decision support for informational purposes only. The content generated by our AI is not a substitute for professional advice — legal, financial, medical, or otherwise.</p>
            <p>We make no guarantees about the accuracy, completeness, or suitability of any AI-generated content for any particular purpose. Always use your own judgment before acting on any recommendation.</p>
          </Section>

          {/* Section 5 */}
          <Section number="05" title="Intellectual Property">
            <p>The Service and its original content, features, and functionality are and will remain the exclusive property of ClarityAI and its licensors. Our trademarks and trade dress may not be used without our prior written permission.</p>
            <p>Content you create using the Service (your decision sessions, inputs, and notes) remains your property. By using the Service, you grant us a limited license to process and store this content solely to provide the Service to you.</p>
          </Section>

          {/* Section 6 */}
          <Section number="06" title="Limitation of Liability">
            <p>To the maximum extent permitted by law, ClarityAI shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the Service.</p>
            <p>Our total liability to you for any claims arising from use of the Service shall not exceed the amount you paid us (if any) in the twelve months preceding the claim.</p>
          </Section>

          {/* Section 7 */}
          <Section number="07" title="Termination">
            <p>We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, if we believe you have violated these Terms or applicable law.</p>
            <p>Upon termination, your right to use the Service will immediately cease. All provisions of these Terms which by their nature should survive termination shall survive.</p>
          </Section>

          {/* Section 8 */}
          <Section number="08" title="Contact Us">
            <p>If you have any questions about these Terms and Conditions, please reach out to us. We are happy to help clarify anything.</p>
            <p>
              You can contact us at{" "}
              <a
                href="mailto:support@clarityai.app"
                style={{ color: "#6b6ef9", textDecoration: "none", fontWeight: 500 }}
              >
                support@clarityai.app
              </a>
            </p>
          </Section>

        </div>

        {/* Footer */}
        <div className="mt-16 pt-8 border-t border-[#e8e8e8] flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-[12.5px] text-[#bbb]">
            © 2026 ClarityAI. All rights reserved.
          </p>
          <a
            href="/login"
            className="text-[13px] text-[#6b6ef9] font-medium hover:underline"
          >
            ← Back to login
          </a>
        </div>

      </div>
    </div>
  );
}

function Section({
  number,
  title,
  children,
}: {
  number: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="bg-white rounded-2xl border border-[#ebebeb] overflow-hidden">
      <div className="flex items-center gap-4 px-6 py-4 border-b border-[#f3f3f3]">
        <span className="text-[11px] font-bold text-[#6b6ef9] bg-[#ededff] px-2.5 py-1 rounded-lg tracking-widest">
          {number}
        </span>
        <h2 className="text-[15.5px] font-semibold text-[#111] tracking-tight">
          {title}
        </h2>
      </div>
      <div
        className="px-6 py-5 text-[14px] text-[#555] leading-relaxed flex flex-col gap-3"
        style={{ listStylePosition: "inside" }}
      >
        {children}
      </div>
    </div>
  );
}